version = 1
SPDX-PackageName = "inquirer-gui"
SPDX-PackageSupplier = "Tomer Epstein <tomer.epstein@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/inquirer-gui"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 SAP SE or an SAP affiliate company and inquirer-gui contributors"
SPDX-License-Identifier = "Apache-2.0"
