name: Release
on:
  push:
    tags:
      - "b*.*.*"

permissions:
  # https://github.com/orgs/community/discussions/68252
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Generate Last Version (only) Changelog
        run: node ./scripts/extract-last-ver-changelog.mjs

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: last-ver-changelog.txt
